<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ptlk.SCADA.Interop\Ptlk.SCADA.Interop\Ptlk.SCADA.Interop.csproj" />
    <ProjectReference Include="..\Ptlk.Web.Hosting\Ptlk.Web.Hosting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Ptlk.RedisScpi.Tests\**\*.cs" />
    <Content Remove="Ptlk.RedisScpi.Tests\**\*" />
    <EmbeddedResource Remove="Ptlk.RedisScpi.Tests\**\*" />
    <None Remove="Ptlk.RedisScpi.Tests\**\*" />
  </ItemGroup>

</Project>
