// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ptlk.RedisScpi.Data;

#nullable disable

namespace Ptlk.RedisScpi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730065956_AddPointOwnershipReleaseJournal")]
    partial class AddPointOwnershipReleaseJournal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Ptlk.RedisScpi.Models.CommandExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActualValueJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("actual_value_json");

                    b.Property<string>("CommandId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("RedisKey")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("redis_key");

                    b.Property<string>("RequestedPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_payload_json");

                    b.Property<string>("ResultPayloadJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_payload_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long?>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_command_executions");

                    b.HasIndex("CommandId")
                        .IsUnique()
                        .HasDatabaseName("ix_command_executions_command_id");

                    b.HasIndex("RedisKey")
                        .HasDatabaseName("ix_command_executions_redis_key");

                    b.HasIndex("Status", "CompletedAt")
                        .HasDatabaseName("ix_command_executions_status_completed_at");

                    b.ToTable("command_executions", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisScpi.Models.PointOwnershipReleaseIntent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("AppliedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("applied_at");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CompletionAction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("completion_action");

                    b.Property<string>("ConverterId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("converter_id");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error_message");

                    b.Property<string>("LastResultCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_result_code");

                    b.Property<long>("NextAttemptAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("RedisKey")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("redis_key");

                    b.Property<long?>("RedisReleasedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("redis_released_at");

                    b.Property<string>("ReplacementRedisKey")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("replacement_redis_key");

                    b.Property<string>("ReplacementSourcePath")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("replacement_source_path");

                    b.Property<long>("RequestedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requested_at");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_point_ownership_release_intents");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_point_ownership_release_intents_operation_id");

                    b.HasIndex("RedisKey")
                        .IsUnique()
                        .HasDatabaseName("ix_point_ownership_release_intents_redis_key")
                        .HasFilter("\"status\" <> 'applied'");

                    b.HasIndex("ReplacementRedisKey")
                        .IsUnique()
                        .HasDatabaseName("ix_point_ownership_release_intents_replacement_redis_key")
                        .HasFilter("\"replacement_redis_key\" IS NOT NULL AND \"status\" <> 'applied'");

                    b.HasIndex("SourcePath", "Status")
                        .HasDatabaseName("ix_point_ownership_release_intents_source_path_status");

                    b.HasIndex("Status", "NextAttemptAt", "RequestedAt")
                        .HasDatabaseName("ix_point_ownership_release_intents_status_next_attempt_at_requested_at");

                    b.ToTable("point_ownership_release_intents", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisScpi.Models.RedisMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("RedisKey")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("redis_key");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_path")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_redis_mappings");

                    b.HasIndex("RedisKey")
                        .IsUnique()
                        .HasDatabaseName("ix_redis_mappings_redis_key");

                    b.HasIndex("SourcePath")
                        .IsUnique()
                        .HasDatabaseName("ix_redis_mappings_source_path");

                    b.ToTable("redis_mappings", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisScpi.Models.ScpiEndpointConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CommandTerminator")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_terminator");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("ConverterId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("converter_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint_id")
                        .UseCollation("NOCASE");

                    b.Property<string>("ErrorCheckMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_check_mode");

                    b.Property<string>("ErrorQueueQuery")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_queue_query");

                    b.Property<int>("PollingIntervalMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("polling_interval_ms");

                    b.Property<string>("ResponseTerminator")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("response_terminator");

                    b.Property<string>("TcpHost")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("tcp_host");

                    b.Property<int?>("TcpPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tcp_port");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout_ms");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("transport");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scpi_endpoint_configs");

                    b.HasIndex("EndpointId")
                        .IsUnique()
                        .HasDatabaseName("ix_scpi_endpoint_configs_endpoint_id");

                    b.ToTable("scpi_endpoint_configs", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisScpi.Models.ScpiEnumOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<int>("ScpiPointConfigId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scpi_point_config_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("value")
                        .UseCollation("NOCASE");

                    b.HasKey("Id")
                        .HasName("pk_scpi_enum_options");

                    b.HasIndex("ScpiPointConfigId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_scpi_enum_options_scpi_point_config_id_code");

                    b.HasIndex("ScpiPointConfigId", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_scpi_enum_options_scpi_point_config_id_value");

                    b.ToTable("scpi_enum_options", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisScpi.Models.ScpiLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CommandId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_id");

                    b.Property<string>("CommandText")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("EndpointId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("operation");

                    b.Property<string>("PointId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("point_id");

                    b.Property<string>("Quality")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("quality");

                    b.Property<string>("ResponseText")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("response_text");

                    b.HasKey("Id")
                        .HasName("pk_scpi_log_entries");

                    b.HasIndex("CommandId")
                        .HasDatabaseName("ix_scpi_log_entries_command_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_scpi_log_entries_created_at");

                    b.HasIndex("EndpointId", "PointId")
                        .HasDatabaseName("ix_scpi_log_entries_endpoint_id_point_id");

                    b.ToTable("scpi_log_entries", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisScpi.Models.ScpiPointConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("access");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_type");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<int>("EndpointConfigId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("endpoint_config_id");

                    b.Property<string>("EnumFormat")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("enum_format");

                    b.Property<bool>("InitialRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("initial_read");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NumberType")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("number_type");

                    b.Property<string>("PointId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("point_id")
                        .UseCollation("NOCASE");

                    b.Property<bool>("PollingEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("polling_enabled");

                    b.Property<int?>("PollingIntervalMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("polling_interval_ms");

                    b.Property<string>("ReadTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("read_template");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_path")
                        .UseCollation("NOCASE");

                    b.Property<string>("StringFormat")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("string_format");

                    b.Property<string>("Unit")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("WriteTemplate")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("write_template");

                    b.HasKey("Id")
                        .HasName("pk_scpi_point_configs");

                    b.HasIndex("SourcePath")
                        .IsUnique()
                        .HasDatabaseName("ix_scpi_point_configs_source_path");

                    b.HasIndex("EndpointConfigId", "PointId")
                        .IsUnique()
                        .HasDatabaseName("ix_scpi_point_configs_endpoint_config_id_point_id");

                    b.ToTable("scpi_point_configs", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisScpi.Models.SystemLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("CommandId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.HasKey("Id")
                        .HasName("pk_system_log_entries");

                    b.HasIndex("CommandId")
                        .HasDatabaseName("ix_system_log_entries_command_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_system_log_entries_created_at");

                    b.HasIndex("Category", "Level")
                        .HasDatabaseName("ix_system_log_entries_category_level");

                    b.ToTable("system_log_entries", (string)null);
                });

            modelBuilder.Entity("Ptlk.RedisScpi.Models.ScpiEnumOption", b =>
                {
                    b.HasOne("Ptlk.RedisScpi.Models.ScpiPointConfig", "ScpiPointConfig")
                        .WithMany("EnumOptions")
                        .HasForeignKey("ScpiPointConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scpi_enum_options_scpi_point_configs_scpi_point_config_id");

                    b.Navigation("ScpiPointConfig");
                });

            modelBuilder.Entity("Ptlk.RedisScpi.Models.ScpiPointConfig", b =>
                {
                    b.HasOne("Ptlk.RedisScpi.Models.ScpiEndpointConfig", "EndpointConfig")
                        .WithMany("Points")
                        .HasForeignKey("EndpointConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scpi_point_configs_scpi_endpoint_configs_endpoint_config_id");

                    b.Navigation("EndpointConfig");
                });

            modelBuilder.Entity("Ptlk.RedisScpi.Models.ScpiEndpointConfig", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("Ptlk.RedisScpi.Models.ScpiPointConfig", b =>
                {
                    b.Navigation("EnumOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
