<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ptlk.RedisScpi.csproj" />
    <ProjectReference Include="..\..\Ptlk.SCADA.Interop\Ptlk.SCADA.Interop\Ptlk.SCADA.Interop.csproj" />
  </ItemGroup>

</Project>
